version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node-app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: